# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

# title: U.R.D.C.DivingTextBook
author: U.R.D.C.琉大ダイビング部
logo: figs/logo.jpg
description: >-
  ダイビング初心者を対象にした教材である。

# 引用文献
bibtex_bibfiles:
  - references.bib

# HTML settings
html:
  favicon: figs/favicon.ico
  extra_navbar: |
    <p>© 2025 University of the Ryukyus Diving Club</p>
  use_issues_button: true
  use_repository_button: true

# “Launch” buttons
launch_buttons:
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com
  notebook_interface: classic   # JupyterLab なら lab



# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://e235221.github.io/DivingClub_textbook/intro.html
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: master # Which branch of the repository should be used when creating links (optional)

# MyST のディレクティブを明示的に有効化
  #  parse:
  #    myst_enable_extensions:
  #      - admonition
  #      - colon_fence
